//
//  DetailWireframe.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 8.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

class DetailWireframe: BaseWireframe {
    
    // TODO: Use tuples for extras if you have more than once parameters
    func show(transitionType: WireframeTransitionType, delegate: DetailPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        let viewController: DetailViewController = UIStoryboard.Main.instantiateViewController()
        
        let networkService = NetworkService.shared
        let interactor = DetailInteractor(networkService: networkService)
        
        let presenter = DetailPresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
