//
//  DetailProtocols.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 8.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller
protocol DetailViewControllerProtocol: BaseViewControllerProtocol {
    func showContentDetail(with model: ContentDetailModel, htmlString: String)
}

// MARK: - Presenter
protocol DetailPresenterViewProtocol: BasePresenterViewProtocol {
    func fetchDetails()
    func tagNumbers() -> Int
    func tag(of index: Int) -> ContentsModel.Tag?
}

protocol DetailPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func loadContentDetail(with model: ContentDetailModel)
}

protocol DetailPresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor
protocol DetailInteractorProtocol: BaseInteractorProtocol {
    func fetchDetails(with contentId: String)
}
