//
//  DetailInteractor.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 8.03.2022.
//
//  Template generated by Burak Cokyildirim

import Foundation

class DetailInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    var presenter: DetailPresenterInteractorProtocol!
    
    // MARK: - Initialization
    override init(networkService: NetworkServiceProtocol? = nil) {
        super.init(networkService: networkService)
    }
}

// MARK: - Extensions

// MARK: - Protocols Implemantations
extension DetailInteractor: DetailInteractorProtocol {
    func fetchDetails(with contentId: String) {
        let url = "\(NetworkConstans.contents)/\(contentId)"
        networkService.executeRequest(
            method: .get, url: url
        ) { [weak self] (result: Result<ContentDetailModel, NetworkError>) in
            switch result {
            case .success(let model):
                self?.presenter.loadContentDetail(with: model)
            case .failure(let error):
                self?.presenter.showNetworkError(with: error)
            }
        }
    }
}
