//
//  LoginProtocols.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 5.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller
protocol LoginViewControllerProtocol: BaseViewControllerProtocol {
    func presentHome()
}

// MARK: - Presenter
protocol LoginPresenterViewProtocol: BasePresenterViewProtocol {
    func login(with username: String?, password: String?)
}

protocol LoginPresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func successLogin(with model: LoginModel)
}

protocol LoginPresenterDelegateProtocol: BasePresenterDelegateProtocol {

}

// MARK: - Interactor
protocol LoginInteractorProtocol: BaseInteractorProtocol {
    func login(username: String, password: String)
}
