//
//  LoginWireframe.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 5.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

class LoginWireframe: BaseWireframe {
    
    func show(transitionType: WireframeTransitionType, delegate: LoginPresenterDelegateProtocol? = nil, extras: Any? = nil) {
        let viewController: LoginViewController = UIStoryboard.Main.instantiateViewController()

        let networkService = NetworkService.shared
        let interactor = LoginInteractor(networkService: networkService)
        
        let presenter = LoginPresenter(
            viewController: viewController, interactor: interactor,
            delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: viewController)
    }
    
}
