//
//  LoginViewController.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 5.03.2022.
//
//  Template generated by Burak Cokyildirim
//

import UIKit

class LoginViewController: BaseViewController {
    
    // MARK: - Outlets
    @IBOutlet weak var userNameTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!

    // MARK: - Dependencies
    var presenter: LoginPresenterViewProtocol!

    // MARK: - Actions
    @IBAction func loginButtonTapped(_ sender: Any) {
        let username = userNameTextField.text
        let password = passwordTextField.text
        presenter.login(with: username, password: password)
    }
}

// MARK: - Protocol Implemantations
extension LoginViewController: LoginViewControllerProtocol {
    func presentHome() {
        HomeWireframe().show(transitionType: .root())
    }
}
