//
//  HomeWireframe.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 7.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

class HomeWireframe: BaseWireframe {
    func show(transitionType: WireframeTransitionType, delegate: HomePresenterDelegateProtocol? = nil, extras: Any? = nil) {
        let viewController: HomeViewController = UIStoryboard.Main.instantiateViewController()
        let navigationController = UINavigationController(rootViewController: viewController)
        
        let networkService = NetworkService.shared

        let interactor = HomeInteractor(networkService: networkService)
        
        let presenter = HomePresenter(viewController: viewController, interactor: interactor, delegate: delegate, extras: extras)
        
        viewController.presenter = presenter
        interactor.presenter = presenter
        
        changeView(transationType: transitionType, viewController: navigationController)
    }
}
