//
//  HomeInteractor.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 7.03.2022.
//
//  Template generated by Burak Cokyildirim

import Foundation

class HomeInteractor: BaseInteractor {
    
    // MARK: - Dependencies
    var presenter: HomePresenterInteractorProtocol!
    
    // MARK: - Initialization
    override init(networkService: NetworkService? = nil) {
        super.init(networkService: networkService)
    }
}

// MARK: - Protocols Implemantations
extension HomeInteractor: HomeInteractorProtocol {
    func fetchContents() {
        let url = NetworkConstans.contents
        networkService.executeRequest(
            method: .get, url: url
        ) { [weak self] (result: Result<ContentsModel, NetworkError>) in
            switch result {
            case .success(let model):
                self?.presenter.loadContents(with: model)
            case .failure(let error):
                self?.presenter.showNetworkError(with: error)
            }
        }
    }
}
