//
//  HomeProtocols.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 7.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller
protocol HomeViewControllerProtocol: BaseViewControllerProtocol {
    func updateView()
}

// MARK: - Presenter
protocol HomePresenterViewProtocol: BasePresenterViewProtocol {
    func logout()
    func fetchContents()
    func numberOfRowsInSection() -> Int
    func content(of index: Int) -> ContentsModel.Content
}

protocol HomePresenterInteractorProtocol: BasePresenterInteractorProtocol {
    func loadContents(with model: ContentsModel)
}

protocol HomePresenterDelegateProtocol: BasePresenterDelegateProtocol {
    
}

// MARK: - Interactor
protocol HomeInteractorProtocol: BaseInteractorProtocol {
    func fetchContents()
}
