//
//  BaseProtocols.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 5.03.2022.
//
//  Template generated by Burak Cokyildirim

import UIKit

// MARK: - View Controller

protocol BaseViewControllerProtocol: AnyObject {
    func showAlert(with errorMessage: String)
    func showLoading()
    func hideLoading()
}

// MARK: - Presenter
protocol BasePresenterViewProtocol: AnyObject {
}

protocol BasePresenterInteractorProtocol: AnyObject {
    func showNetworkError(with error: NetworkError)    
}

protocol BasePresenterDelegateProtocol: AnyObject {
}

// MARK: - Interactor
protocol BaseInteractorProtocol: AnyObject {
}
