//
//  BaseInteractor.swift
//  Kick-Off
//
//  Created by Burak Çokyıldırım on 5.03.2022.
//
//  Template generated by Burak Cokyildirim

import Foundation

class BaseInteractor {

    // MARK: - Properties
    internal var networkService: NetworkService!

    init(networkService: NetworkService?) {
        if let networkService = networkService {
            self.networkService = networkService
        }
    }
}

// MARK: - Extensions

// MARK: - Protocols Implemantations
extension BaseInteractor: BaseInteractorProtocol {
}
